import os
import time
import requests

GEMINI_KEY = os.environ["GEMINI_API_KEY"]
BUFFER_KEY = os.environ["BUFFER_API_KEY"]

PROMPT = """
Write one LinkedIn post for Matvei Shakhurdin.

About Matvei:
- Senior Project / Delivery Manager
- 4+ years in project management
- background in design, web development, marketing and fintech projects
- interested in AI, automation, processes, team management and delivery
- wants to move from agency work toward strong product teams

The post should help position him as a strong practical project manager.

Writing style:
- English
- natural and human
- conversational, but professional
- practical rather than motivational
- no corporate bullshit
- no obvious AI language
- no "not only... but also"
- no "in today's fast-paced world"
- no "game-changer"
- no "unlock"
- no fake personal stories
- no emojis
- no hashtags
- avoid excessive bullet points
- use medium dashes – not em dashes —
- around 700–1300 characters
- strong first 1–2 lines
- one clear idea per post
- do not put a period at the very end

Topics can include:
AI for project managers, automation, project delivery, processes,
stakeholder communication, design management, team workload,
project mistakes, practical PM lessons, Agile, Scrum, Jira,
agency vs product work, or working with creative/dev teams.

Return ONLY the finished LinkedIn post.
"""


# -------------------------
# GEMINI
# -------------------------

def generate_post():
    # If one model is temporarily unavailable, try another free Flash model.
    models = [
        "gemini-3.8-flash",
        "gemini-3.7-flash",
        "gemini-3.6-flash",
        "gemini-3.5-flash",
    ]

    url = "https://generativelanguage.googleapis.com/v1beta/interactions"

    for model in models:
        for attempt in range(3):
            print(f"Trying Gemini: {model}, attempt {attempt + 1}")

            response = requests.post(
                url,
                headers={
                    "x-goog-api-key": GEMINI_KEY,
                    "Content-Type": "application/json",
                },
                json={
                    "model": model,
                    "input": PROMPT,
                    "generation_config": {
                        "temperature": 1.0
                    }
                },
                timeout=120,
            )

            # Temporary Google error — retry.
            if response.status_code in [429, 500, 502, 503, 504]:
                print(
                    f"Gemini temporarily unavailable: "
                    f"{response.status_code} {response.text[:300]}"
                )
                time.sleep(5 * (attempt + 1))
                continue

            # Authentication problem.
            if response.status_code in [401, 403]:
                raise RuntimeError(
                    "Gemini API key was rejected. "
                    "Create a new API key in Google AI Studio and replace "
                    "GEMINI_API_KEY in GitHub Secrets.\n\n"
                    + response.text
                )

            response.raise_for_status()
            data = response.json()

            # Find the final text generated by Gemini.
            texts = []

            for step in data.get("steps", []):
                if step.get("type") == "model_output":
                    for content in step.get("content", []):
                        if (
                            content.get("type") == "text"
                            and content.get("text")
                        ):
                            texts.append(content["text"])

            if texts:
                post = "\n".join(texts).strip()
                print("\nPOST GENERATED:\n")
                print(post)
                return post

            print("Gemini returned no text:")
            print(data)

    raise RuntimeError("All Gemini models failed after retries.")


# -------------------------
# BUFFER
# -------------------------

def buffer_request(query, variables=None):
    response = requests.post(
        "https://api.buffer.com",
        headers={
            "Authorization": f"Bearer {BUFFER_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "query": query,
            "variables": variables or {},
        },
        timeout=60,
    )

    response.raise_for_status()

    result = response.json()

    if result.get("errors"):
        raise RuntimeError(
            "Buffer API error:\n"
            + str(result["errors"])
        )

    return result["data"]


def get_linkedin_channel():
    # Get Buffer organization.
    data = buffer_request(
        """
        query GetOrganizations {
          account {
            organizations {
              id
              name
            }
          }
        }
        """
    )

    organizations = data["account"]["organizations"]

    if not organizations:
        raise RuntimeError("No Buffer organization found.")

    organization_id = organizations[0]["id"]

    print(f"Buffer organization: {organizations[0]['name']}")

    # Get connected social accounts.
    data = buffer_request(
        """
        query GetChannels($organizationId: OrganizationId!) {
          channels(input: { organizationId: $organizationId }) {
            id
            name
            service
          }
        }
        """,
        {
            "organizationId": organization_id
        },
    )

    channels = data["channels"]

    print("Connected Buffer channels:")
    for channel in channels:
        print(
            f"- {channel['name']} / "
            f"{channel['service']} / "
            f"{channel['id']}"
        )

    linkedin_channels = [
        channel
        for channel in channels
        if str(channel["service"]).lower() == "linkedin"
    ]

    if not linkedin_channels:
        raise RuntimeError(
            "LinkedIn is not connected to Buffer."
        )

    linkedin = linkedin_channels[0]

    print(f"Using LinkedIn: {linkedin['name']}")

    return linkedin["id"]


def create_buffer_draft(channel_id, post):
    mutation = """
    mutation CreateDraftPost($input: CreatePostInput!) {
      createPost(input: $input) {
        ... on PostActionSuccess {
          post {
            id
            text
          }
        }

        ... on MutationError {
          message
        }
      }
    }
    """

    data = buffer_request(
        mutation,
        {
            "input": {
                "text": post,
                "channelId": channel_id,
                "schedulingType": "automatic",
                "mode": "addToQueue",
                "saveToDraft": True,
                "aiAssisted": True,
            }
        },
    )

    result = data["createPost"]

    if result.get("message"):
        raise RuntimeError(
            "Buffer could not create draft: "
            + result["message"]
        )

    print("\nSUCCESS!")
    print("Draft created in Buffer.")
    print(result)


# -------------------------
# RUN
# -------------------------

post = generate_post()

linkedin_channel_id = get_linkedin_channel()

create_buffer_draft(
    linkedin_channel_id,
    post
)
